version: '3'

services:
  main:
    image: aperove/oibot:dev
    container_name: oibot
    restart: unless-stopped
    
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bot
    environment:
    command: python main.py
